# Generated by Django 4.1.6 on 2023-02-10 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_patient_delete_appointment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
