# Generated by Django 4.1.6 on 2023-02-11 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule', models.CharField(max_length=255, verbose_name='График работы')),
                ('workload', models.CharField(max_length=255, verbose_name='Загруженность по приемам')),
                ('price', models.IntegerField(verbose_name='Стоимость приема')),
            ],
            options={
                'verbose_name': 'Карточка',
                'verbose_name_plural': 'Карточки',
            },
        ),
    ]
